include ../.mm/magic

LIB_PKGMODULES=simplelib
PROJECT_NAME=bsc2
PROJECT_DESCRIPTION=An example library with pkg-config dependencies
SYMBOL_PREFIX=basic

LIB_CFILES=$(wildcard lib/*.c)
BIN_CFILES=$(wildcard bin/*.c)

include ../.mm/lib
include ../.mm/bin
include ../.mm/pkgconfig-generator.mk
